"""empty message

<<<<<<<< HEAD:migrations/versions/3022bf7465e1_.py
Revision ID: 3022bf7465e1
Revises: 
Create Date: 2025-06-23 08:58:40.144981
========
Revision ID: 6fd51ba163c3
Revises: 
Create Date: 2025-06-19 16:09:44.561587
>>>>>>>> b767b1bd2cafaa4ad171ece5b09177b2d7013a89:migrations/versions/6fd51ba163c3_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/3022bf7465e1_.py
revision = '3022bf7465e1'
========
revision = '6fd51ba163c3'
>>>>>>>> b767b1bd2cafaa4ad171ece5b09177b2d7013a89:migrations/versions/6fd51ba163c3_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onlinegames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('difficulty_levels', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=350), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=90), nullable=True),
    sa.Column('dateofbirth', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_image', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('onlinegame_id', sa.Integer(), nullable=True),
    sa.Column('game_api_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['onlinegame_id'], ['onlinegames.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iasessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=60), nullable=True),
    sa.Column('difficulty_levels', sa.String(length=60), nullable=True),
    sa.Column('character_name', sa.String(length=60), nullable=False),
    sa.Column('character_class', sa.String(length=60), nullable=False),
    sa.Column('experience_gained', sa.Integer(), nullable=True),
    sa.Column('story_branch', sa.String(length=200), nullable=True),
    sa.Column('result', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onlinestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessions_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('stalemate', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('move_count', sa.Integer(), nullable=False),
    sa.Column('last_played', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('online_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['online_game_id'], ['onlinegames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usercontacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('storeItem_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['storeItem_id'], ['store_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sessions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessions_id'], ['iasessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iaevents')
    op.drop_table('cartitem')
    op.drop_table('usercontacts')
    op.drop_table('onlinestats')
    op.drop_table('iasessions')
    op.drop_table('favorites')
    op.drop_table('cart')
    op.drop_table('users')
    op.drop_table('store_item')
    op.drop_table('onlinegames')
    op.drop_table('game_purchase')
    # ### end Alembic commands ###
