"""empty message

Revision ID: d2e210992341
Revises: 0a98ad712f04
Create Date: 2025-05-22 19:40:35.681349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e210992341'
down_revision = '0a98ad712f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onlinegame_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_onlinegames_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'onlinegames', ['onlinegame_id'], ['id'])
        batch_op.drop_column('onlinegames_id')

    with op.batch_alter_table('iasessions', schema=None) as batch_op:
        batch_op.alter_column('character_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    with op.batch_alter_table('onlinegames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.drop_column('descrption')

    with op.batch_alter_table('onlinestats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stalemate', sa.Integer(), nullable=False))
        batch_op.drop_column('stolemate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onlinestats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stolemate', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('stalemate')

    with op.batch_alter_table('onlinegames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrption', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('iasessions', schema=None) as batch_op:
        batch_op.alter_column('character_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onlinegames_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_onlinegames_id_fkey', 'onlinegames', ['onlinegames_id'], ['id'])
        batch_op.drop_column('onlinegame_id')

    # ### end Alembic commands ###
