"""empty message

Revision ID: e7a28387d6b7
Revises: 9a457fa34929
Create Date: 2025-05-22 10:35:37.619477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a28387d6b7'
down_revision = '9a457fa34929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_image')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
